#!/bin/sh
set -e

echo "Running pre-commit checks..."

staged_go_files=$(git diff --cached --name-only --diff-filter=ACMR -- '*.go')

if [ -z "$staged_go_files" ]; then
    echo "No staged Go files. Skipping linter."
    exit 0
fi

packages=$(echo "$staged_go_files" | xargs -n1 dirname | sort -u | sed 's|^|./|')

echo "Running linter on staged packages..."
echo "$packages" | tr '\n' '\0' | xargs -0 golangci-lint run

echo "All checks passed."
