# UI Related Stuffs
GeneralConfig:
  ServerName: "GoCP"

# Session/Token Lifetime
TTL:
  Session: "24h"
  Verification: "30m"
  PasswordReset: "1h"
  EmailChange: "24h"

# Action Cooldowns
Cooldown:
  VerificationResend: "60s"
  PasswordResetRequest: "30m"
  PasswordChange: "168h"
  EmailChangeRequest: "60s"
  EmailChange: "336h"

# Mail Stuffs
MailerConfig:
  FromAddress: "noreply@your-server.example"
