FROM golang:1.26-alpine AS builder

# Live reloading for Go
RUN go install github.com/air-verse/air@latest

WORKDIR /app
COPY go.mod go.sum* ./
RUN go mod download

COPY . .

CMD ["air", "-c", ".air.toml"]
