FROM golang:1.26-alpine AS builder

RUN adduser -D -u 10001 app

# Live reloading for Go
RUN go install github.com/air-verse/air@latest

WORKDIR /app
COPY go.mod go.sum* ./
RUN go mod download

COPY . .

RUN mkdir -p /app/tmp \
    && chown -R app:app /app /go

USER app

CMD ["air", "-c", ".air.toml"]
