package main

import (
	"strings"
	"testing"
)

func TestEmitThemeOverride_EmbedsDefaultAndOverridesMethods(t *testing.T) {
	t.Parallel()

	overrides := []Component{
		{
			Method:     "AccountLoginPage",
			ImportPath: "github.com/hayakawakaki/go-racp/themes/sample/features/account/transport",
			ImportName: "sampleaccount",
			FuncName:   "AccountLoginPage",
			Params:     "props sampleaccount.LoginProps",
			Args:       "props",
		},
	}

	got := emitThemeOverride("sample", overrides)

	for _, want := range []string{
		"// Code generated by themegen. DO NOT EDIT.",
		"//go:build theme_sample",
		"package theme",
		`sampleaccount "github.com/hayakawakaki/go-racp/themes/sample/features/account/transport"`,
		"type SampleTheme struct{ DefaultTheme }",
		"var _ Theme = SampleTheme{}",
		"func (SampleTheme) AccountLoginPage(props sampleaccount.LoginProps) templ.Component {",
		"return sampleaccount.AccountLoginPage(props)",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("emitThemeOverride output missing %q\n--- output ---\n%s", want, got)
		}
	}
}

func TestEmitThemeOverride_EmptyOverridesStillEmitsStruct(t *testing.T) {
	t.Parallel()

	got := emitThemeOverride("sample", nil)

	for _, want := range []string{
		"//go:build theme_sample",
		"type SampleTheme struct{ DefaultTheme }",
		"var _ Theme = SampleTheme{}",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("empty-override output missing %q\n--- output ---\n%s", want, got)
		}
	}
}
