# UI Related Stuffs
App:
  ServerName: "GoCP"
  Timezone: "UTC"
  Theme: "default"
  Gepard: false
  Rates:
    ExpRate: 100
    JobRate: 100
    DropRateCommon: 100
    DropRateHeal: 100
    DropRateUsable: 100
    DropRateEquip: 100
    DropRateCard: 100
    DropRateCardMVP: 100

# Mail Stuffs
Mailer:
  FromAddress: "noreply@your-server.example"

# Default save location used by /characters/{id}/location
DefaultLocation:
  Map: "prontera"
  X: 156
  Y: 191
