// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"strconv"
	"strings"
)

type PaginationSize string

const (
	PaginationSizeSM PaginationSize = "sm"
	PaginationSizeMD PaginationSize = "md"
	PaginationSizeLG PaginationSize = "lg"
)

type PaginationColor string

const (
	PaginationColorNeutral PaginationColor = "neutral"
	PaginationColorBlue    PaginationColor = "blue"
	PaginationColorRed     PaginationColor = "red"
	PaginationColorYellow  PaginationColor = "yellow"
	PaginationColorGreen   PaginationColor = "green"
	PaginationColorOrange  PaginationColor = "orange"
	PaginationColorPurple  PaginationColor = "purple"
	PaginationColorPink    PaginationColor = "pink"
	PaginationColorIndigo  PaginationColor = "indigo"
	PaginationColorTeal    PaginationColor = "teal"
	PaginationColorZinc    PaginationColor = "zinc"
	PaginationColorStone   PaginationColor = "stone"
)

type PaginationProps struct {
	Attrs       templ.Attributes
	LinkAttrs   templ.Attributes
	HrefPattern string
	Class       string
	Size        PaginationSize
	Color       PaginationColor
	Page        int
	TotalPages  int
}

var paginationInputColorMap = map[PaginationColor]string{
	PaginationColorNeutral: "bg-slate-50 border-slate-300 focus-visible:ring-slate-400 dark:bg-slate-800 dark:border-slate-700 dark:focus-visible:ring-slate-500",
	PaginationColorBlue:    "bg-blue-50 border-blue-200 focus-visible:ring-blue-500 dark:bg-blue-950 dark:border-blue-800",
	PaginationColorRed:     "bg-red-50 border-red-200 focus-visible:ring-red-500 dark:bg-red-950 dark:border-red-800",
	PaginationColorYellow:  "bg-yellow-50 border-yellow-200 focus-visible:ring-yellow-500 dark:bg-yellow-950 dark:border-yellow-800",
	PaginationColorGreen:   "bg-green-50 border-green-200 focus-visible:ring-green-500 dark:bg-green-950 dark:border-green-800",
	PaginationColorOrange:  "bg-orange-50 border-orange-200 focus-visible:ring-orange-500 dark:bg-orange-950 dark:border-orange-800",
	PaginationColorPurple:  "bg-purple-50 border-purple-200 focus-visible:ring-purple-500 dark:bg-purple-950 dark:border-purple-800",
	PaginationColorPink:    "bg-pink-50 border-pink-200 focus-visible:ring-pink-500 dark:bg-pink-950 dark:border-pink-800",
	PaginationColorIndigo:  "bg-indigo-50 border-indigo-200 focus-visible:ring-indigo-500 dark:bg-indigo-950 dark:border-indigo-800",
	PaginationColorTeal:    "bg-teal-50 border-teal-200 focus-visible:ring-teal-500 dark:bg-teal-950 dark:border-teal-800",
	PaginationColorZinc:    "bg-zinc-100 border-zinc-300 focus-visible:ring-zinc-500 dark:bg-zinc-800 dark:border-zinc-700",
	PaginationColorStone:   "bg-stone-100 border-stone-300 focus-visible:ring-stone-500 dark:bg-stone-800 dark:border-stone-700",
}

func paginationInputColorClasses(color PaginationColor) string {
	if c, ok := paginationInputColorMap[color]; ok {
		return c
	}

	return paginationInputColorMap[PaginationColorNeutral]
}

const paginationPagePlaceholder = "__PAGE__"

func paginationPattern(p PaginationProps) string {
	if p.HrefPattern != "" {
		return p.HrefPattern
	}

	return "?page=" + paginationPagePlaceholder
}

func paginationHref(p PaginationProps, page int) templ.SafeURL {
	if page < 1 {
		page = 1
	}

	if page > p.TotalPages {
		page = p.TotalPages
	}

	return templ.SafeURL(strings.ReplaceAll(paginationPattern(p), paginationPagePlaceholder, strconv.Itoa(page)))
}

func paginationGroupSize(size PaginationSize) string {
	switch size {
	case PaginationSizeSM:
		return "h-7 text-xs"
	case PaginationSizeLG:
		return "h-11 text-base"
	default:
		return "h-9 text-sm"
	}
}

func paginationInputSize(size PaginationSize) string {
	switch size {
	case PaginationSizeSM:
		return "h-5 w-8"
	case PaginationSizeLG:
		return "h-9 w-12"
	default:
		return "h-7 w-11"
	}
}

func paginationGroupClasses(p PaginationProps) string {
	base := "inline-flex items-center gap-1 pl-1 pr-2 rounded-md border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 shadow-sm"

	return Merge(base, paginationGroupSize(p.Size))
}

func paginationInputClasses(p PaginationProps) string {
	base := "text-slate-900 dark:text-slate-100 text-center border rounded-sm focus:outline-none focus-visible:ring-1 [-moz-appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"

	return Merge(base, paginationInputSize(p.Size), paginationInputColorClasses(p.Color))
}

func paginationClasses(p PaginationProps) string {
	return Merge("inline-flex items-center gap-1", p.Class)
}

func paginationStep(p PaginationProps, target int, label string, icon templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = Button(ButtonProps{
			Variant:   ButtonSubtle,
			Color:     ButtonColor(p.Color),
			Size:      ButtonSize(p.Size),
			Rounded:   ButtonRoundedMD,
			AriaLabel: label,
			LeftIcon:  icon,
			Disabled:  target < 1 || target > p.TotalPages || target == p.Page,
			Href:      string(paginationHref(p, target)),
			Attrs:     p.LinkAttrs,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func Pagination(p PaginationProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if p.TotalPages > 0 {
			var templ_7745c5c3_Var3 = []any{paginationClasses(p)}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var3...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var3).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/platform/ui/pagination.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" aria-label=\"Pagination\" x-data=\"pagination\" data-pagination-max=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(strconv.Itoa(p.TotalPages))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/platform/ui/pagination.templ`, Line: 147, Col: 51}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" data-pagination-pattern=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(paginationPattern(p))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/platform/ui/pagination.templ`, Line: 148, Col: 49}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, p.Attrs)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, ">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = paginationStep(p, 1, "First page", Icon("chevrons-left")).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = paginationStep(p, p.Page-1, "Previous page", Icon("chevron-left")).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 = []any{paginationGroupClasses(p)}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var7...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var7).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/platform/ui/pagination.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var9 = []any{paginationInputClasses(p)}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var9...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<input type=\"number\" class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var10 string
			templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var9).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/platform/ui/pagination.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var11 string
			templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(strconv.Itoa(p.Page))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/platform/ui/pagination.templ`, Line: 157, Col: 33}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\" min=\"1\" max=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var12 string
			templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(strconv.Itoa(p.TotalPages))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/platform/ui/pagination.templ`, Line: 159, Col: 37}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "\" aria-label=\"Jump to page\" @change=\"go($event.target.value)\" @keydown.enter.prevent=\"go($event.target.value)\"> <span class=\"text-slate-500 dark:text-slate-400 select-none\">of ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var13 string
			templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(strconv.Itoa(p.TotalPages))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/platform/ui/pagination.templ`, Line: 164, Col: 96}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</span></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = paginationStep(p, p.Page+1, "Next page", Icon("chevron-right")).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = paginationStep(p, p.TotalPages, "Last page", Icon("chevrons-right")).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</nav>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

func PaginationPreview() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var14 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var14 == nil {
			templ_7745c5c3_Var14 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<div class=\"space-y-8\"><section class=\"space-y-4\"><h2 class=\"text-lg font-semibold\">Basic</h2>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Pagination(PaginationProps{Page: 5, TotalPages: 10}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</section><section class=\"space-y-4\"><h2 class=\"text-lg font-semibold\">Large totals</h2>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Pagination(PaginationProps{Page: 250, TotalPages: 999}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</section><section class=\"space-y-4\"><h2 class=\"text-lg font-semibold\">Single page</h2>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Pagination(PaginationProps{Page: 1, TotalPages: 1}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "</section><section class=\"space-y-4\"><h2 class=\"text-lg font-semibold\">Sizes</h2><div class=\"flex flex-col items-start gap-3\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Pagination(PaginationProps{Page: 3, TotalPages: 20, Size: PaginationSizeSM}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Pagination(PaginationProps{Page: 3, TotalPages: 20, Size: PaginationSizeMD}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Pagination(PaginationProps{Page: 3, TotalPages: 20, Size: PaginationSizeLG}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "</div></section><section class=\"space-y-4\"><h2 class=\"text-lg font-semibold\">Colors</h2><div class=\"flex flex-col items-start gap-3\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Pagination(PaginationProps{Page: 3, TotalPages: 20, Color: PaginationColorNeutral}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Pagination(PaginationProps{Page: 3, TotalPages: 20, Color: PaginationColorBlue}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Pagination(PaginationProps{Page: 3, TotalPages: 20, Color: PaginationColorGreen}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Pagination(PaginationProps{Page: 3, TotalPages: 20, Color: PaginationColorRed}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Pagination(PaginationProps{Page: 3, TotalPages: 20, Color: PaginationColorPurple}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "</div></section><section class=\"space-y-4\"><h2 class=\"text-lg font-semibold\">Custom URL (HrefPattern)</h2><p class=\"text-sm text-slate-500 dark:text-slate-400\">Replace the default <code>?page=__PAGE__</code> with any URL shape.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Pagination(PaginationProps{
			Page:        3,
			TotalPages:  20,
			HrefPattern: "/items/page/__PAGE__",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "</section><section class=\"space-y-4\"><h2 class=\"text-lg font-semibold\">HTMX (hx-boost wrapper)</h2><p class=\"text-sm text-slate-500 dark:text-slate-400\">Wrap in <code>hx-boost=\"true\"</code> to intercept anchor clicks. The jump input still does a full navigation (use a custom @change override if you need HTMX there too).</p><div hx-boost=\"true\" hx-target=\"#results\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Pagination(PaginationProps{Page: 5, TotalPages: 20}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "</div></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func init() {
	Register(Component{
		Name:   "pagination",
		Title:  "Pagination",
		Render: PaginationPreview,
	})
}

var _ = templruntime.GeneratedTemplate
