CREATE TABLE IF NOT EXISTS cp_storage (
    id           INT       UNSIGNED NOT NULL AUTO_INCREMENT,
    account_id   INT       UNSIGNED NOT NULL DEFAULT 0,
    nameid       INT       UNSIGNED NOT NULL DEFAULT 0,
    amount       SMALLINT  UNSIGNED NOT NULL DEFAULT 0,
    equip        INT       UNSIGNED NOT NULL DEFAULT 0,
    identify     SMALLINT  UNSIGNED NOT NULL DEFAULT 0,
    refine       TINYINT   UNSIGNED NOT NULL DEFAULT 0,
    attribute    TINYINT   UNSIGNED NOT NULL DEFAULT 0,
    card0        INT       UNSIGNED NOT NULL DEFAULT 0,
    card1        INT       UNSIGNED NOT NULL DEFAULT 0,
    card2        INT       UNSIGNED NOT NULL DEFAULT 0,
    card3        INT       UNSIGNED NOT NULL DEFAULT 0,
    option_id0   SMALLINT           NOT NULL DEFAULT 0,
    option_val0  SMALLINT           NOT NULL DEFAULT 0,
    option_parm0 TINYINT            NOT NULL DEFAULT 0,
    option_id1   SMALLINT           NOT NULL DEFAULT 0,
    option_val1  SMALLINT           NOT NULL DEFAULT 0,
    option_parm1 TINYINT            NOT NULL DEFAULT 0,
    option_id2   SMALLINT           NOT NULL DEFAULT 0,
    option_val2  SMALLINT           NOT NULL DEFAULT 0,
    option_parm2 TINYINT            NOT NULL DEFAULT 0,
    option_id3   SMALLINT           NOT NULL DEFAULT 0,
    option_val3  SMALLINT           NOT NULL DEFAULT 0,
    option_parm3 TINYINT            NOT NULL DEFAULT 0,
    option_id4   SMALLINT           NOT NULL DEFAULT 0,
    option_val4  SMALLINT           NOT NULL DEFAULT 0,
    option_parm4 TINYINT            NOT NULL DEFAULT 0,
    expire_time  INT       UNSIGNED NOT NULL DEFAULT 0,
    bound        TINYINT   UNSIGNED NOT NULL DEFAULT 0,
    unique_id    BIGINT    UNSIGNED NOT NULL DEFAULT 0,
    enchantgrade TINYINT   UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_cp_storage_account_nameid (account_id, nameid)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cp_storage_escrow (
    id           BIGINT    UNSIGNED NOT NULL AUTO_INCREMENT,
    account_id   INT       UNSIGNED NOT NULL DEFAULT 0,
    listing_ref  BIGINT             NOT NULL,
    nameid       INT       UNSIGNED NOT NULL DEFAULT 0,
    amount       SMALLINT  UNSIGNED NOT NULL DEFAULT 0,
    equip        INT       UNSIGNED NOT NULL DEFAULT 0,
    identify     SMALLINT  UNSIGNED NOT NULL DEFAULT 0,
    refine       TINYINT   UNSIGNED NOT NULL DEFAULT 0,
    attribute    TINYINT   UNSIGNED NOT NULL DEFAULT 0,
    card0        INT       UNSIGNED NOT NULL DEFAULT 0,
    card1        INT       UNSIGNED NOT NULL DEFAULT 0,
    card2        INT       UNSIGNED NOT NULL DEFAULT 0,
    card3        INT       UNSIGNED NOT NULL DEFAULT 0,
    option_id0   SMALLINT           NOT NULL DEFAULT 0,
    option_val0  SMALLINT           NOT NULL DEFAULT 0,
    option_parm0 TINYINT            NOT NULL DEFAULT 0,
    option_id1   SMALLINT           NOT NULL DEFAULT 0,
    option_val1  SMALLINT           NOT NULL DEFAULT 0,
    option_parm1 TINYINT            NOT NULL DEFAULT 0,
    option_id2   SMALLINT           NOT NULL DEFAULT 0,
    option_val2  SMALLINT           NOT NULL DEFAULT 0,
    option_parm2 TINYINT            NOT NULL DEFAULT 0,
    option_id3   SMALLINT           NOT NULL DEFAULT 0,
    option_val3  SMALLINT           NOT NULL DEFAULT 0,
    option_parm3 TINYINT            NOT NULL DEFAULT 0,
    option_id4   SMALLINT           NOT NULL DEFAULT 0,
    option_val4  SMALLINT           NOT NULL DEFAULT 0,
    option_parm4 TINYINT            NOT NULL DEFAULT 0,
    expire_time  INT       UNSIGNED NOT NULL DEFAULT 0,
    bound        TINYINT   UNSIGNED NOT NULL DEFAULT 0,
    unique_id    BIGINT    UNSIGNED NOT NULL DEFAULT 0,
    enchantgrade TINYINT   UNSIGNED NOT NULL DEFAULT 0,
    created_at   TIMESTAMP          NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_cp_storage_escrow_ref (listing_ref),
    KEY idx_cp_storage_escrow_account (account_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cp_storage_lock (
    account_id INT     UNSIGNED NOT NULL,
    is_locked  TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (account_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cp_delivery_applied (
    leg_id BIGINT NOT NULL,
    PRIMARY KEY (leg_id)
) ENGINE=InnoDB;
