Branding:
  Logo: ""
  Discord: "https://discord.gg/"

Navbar:
  Items:
    - Label: "Home"
      Href: "/"
      Icon: "home"
    - Label: "News"
      Href: "/news"
      Icon: "news"
    - Label: "Database"
      Icon: "db"
      Subitems:
        - Label: "Item Database"
          Href: "/items"
        - Label: "Mob Database"
          Href: "/mobs"
