// Code generated by themegen. DO NOT EDIT.

package themesdefault

import (
	"net/http"

	"github.com/hayakawakaki/go-racp/internal/platform/httpx"
)

func MountRoutes(_ *http.ServeMux, _ httpx.Layout) {
}
